### ISSUE TITLE
Incorrect bonding when adding two ibuprofen molecule in 02_ibuprofen_solvent.ipynb

### ISSUE THREAD

**Issue by ghost** [molmod/openmm-tutorial-msbs#3]
Hi,

In the exercise of solvated ibuprofen, when I added two ibuprofen molecules (it's normal when adding only one ibuprofen), the packmol generates system with wrong bonding. Please see attached image.
Also, when i tried to substitute water with dimethyl ether, it raised the following error when assigning forcefield parameters: 

> ValueError: No template found for residue 2 (HOH).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.

Could you please help? Thanks!

![image](https://user-images.githubusercontent.com/56269871/105769165-52be6380-5f55-11eb-93bc-2440bd5ac715.png)

**Comment by tovrstra** [comment]
I can reproduce the issue after an upgrade of my conda environment. (The notebook used to work when I originally wrote it.) This must somehow be related to packages that have been updated. When downgrading to MDTraj 1.9.4, the issue with the bonds is resolved but the notebook still does not work as it should.

**Comment by Griffon-Github** [comment]
Thanks for your reply. I tried to run packmol directly from the installed executable (instead of importing the python module) to generate the initial configuration.  And the bonding issue can be also fixed.  And I used the following code to register the residue template and assign parameters. Everything seems to work now.
```
from openmmforcefields.generators import SMIRNOFFTemplateGenerator
forcefield = ForceField('amber14-all.xml','amber14/tip3pfb.xml') 
smirnoff = SMIRNOFFTemplateGenerator(molecules=molecules)
forcefield.registerTemplateGenerator(smirnoff.generator)
```
But this cause some other issues. When I choose dimethy ether as solvent and ran the simmulation, it raised the exception of "particle coordinate is nan".

**Comment by tovrstra** [comment]
@Griffon-Github I've updated many parts of the notebooks, in preparation for a new edition of the course. I've tested everything again with latest versions of all software packages. It seems that the problem has vanished again. I'm going to close the issue. If you can still reproduce it, feel free to re-open the issue or ping me.
